/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package viewChucNangChinh;

import Model.HoaDon;
import Repository.HoaDonRepo;
import Repository.HoaDonChiTietRepo;
import Model.HoaDonChiTiet;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import com.itextpdf.text.Document; // Lớp để tạo tài liệu PDF
import com.itextpdf.text.DocumentException; // Xử lý ngoại lệ khi tạo PDF
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph; // Thêm đoạn văn bản vào PDF
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.PdfPTable; // Tạo bảng trong PDF
import com.itextpdf.text.pdf.PdfWriter; // Ghi nội dung vào file PDF
import javax.swing.*; // Thư viện để sử dụng các thành phần GUI như JOptionPane
import java.io.FileOutputStream; // Để ghi dữ liệu ra file
import java.io.IOException; // Xử lý ngoại lệ khi làm việc với file
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;

/**
 *
 * @author Hoang
 */
public class ViewHoaDon extends javax.swing.JPanel implements HoaDonUpdateListener {

    /**
     * Creates new form ViewHoaDon
     */
    private HoaDonRepo hoaDonRepo;
    private HoaDonChiTietRepo chiTietHoaDonRepo;

    public ViewHoaDon() {
        initComponents();
        hoaDonRepo = new HoaDonRepo();  // Khởi tạo repository để lấy dữ liệu
        chiTietHoaDonRepo = new HoaDonChiTietRepo();  // Repository cho chi tiết hóa đơn
        loadHoaDonList();
        HoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HoaDonMouseClicked(evt);  // Gọi phương thức xử lý sự kiện khi click vào bảng
            }
        });
    }

    @Override
    public void onHoaDonUpdated() {
        loadHoaDonList(); // Tải lại danh sách hóa đơn đã thanh toán
        // Nếu muốn tự động chọn hóa đơn vừa thanh toán, thêm logic tại đây
    }

    public interface HoaDonObserver {

        void updateHoaDon();
    }

    public void loadHoaDonList() {
        DefaultTableModel model = (DefaultTableModel) HoaDon.getModel();
        model.setRowCount(0);
        ArrayList<HoaDon> hoaDons = hoaDonRepo.getListHDHT(); // Chỉ lấy hóa đơn đã thanh toán
        for (HoaDon hoaDon : hoaDons) {
            model.addRow(new Object[]{
                hoaDon.getMaHoaDon(),
                hoaDon.getMaKhachHang(),
                hoaDon.getMaNhanVien(),
                hoaDon.getMaPhieuGiamGia(),
                hoaDon.getNgayTao(),
                hoaDon.getTongTien(),
                hoaDon.getSoTienGiam(),
                hoaDon.getThanhTien()
            });
        }
    }

    private void loadChiTietHoaDon(String maHoaDon) {
        DefaultTableModel model = (DefaultTableModel) ChiTietHoaDon.getModel();
        model.setRowCount(0);

        ArrayList<HoaDonChiTiet> chiTietList = chiTietHoaDonRepo.getChiTietByHoaDon(maHoaDon);

        for (HoaDonChiTiet chiTiet : chiTietList) {
            model.addRow(new Object[]{
                chiTiet.getMaSanPham(),
                chiTiet.getTenSanPham(),
                chiTiet.getSoLuong(),
                chiTiet.getDonGia(),
                chiTiet.getThanhTien()
            });
        }
    }

    private void HoaDonMouseClicked(java.awt.event.MouseEvent evt) {
        int selectedRow = HoaDon.getSelectedRow();
        if (selectedRow != -1) {
            String maHoaDon = (String) HoaDon.getValueAt(selectedRow, 0);
            loadChiTietHoaDon(maHoaDon);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        Xuat = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        MaHoaDon = new javax.swing.JTextField();
        MaNhanVien = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        MaKhachHang = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ThoiGianTu = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        ThoiGianDen = new com.toedter.calendar.JDateChooser();
        btnTimKiem = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        HoaDon = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        ChiTietHoaDon = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("QUẢN LÍ HOÁ ĐƠN");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 27, -1, 27));

        Xuat.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        Xuat.setText("In hoá đơn");
        Xuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XuatActionPerformed(evt);
            }
        });
        add(Xuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(722, 19, -1, 45));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Mã hoá đơn");

        jLabel4.setText("Mã nhân viên");

        jLabel5.setText("Mã khách hàng");

        jLabel6.setText("Thời gian từ");

        ThoiGianTu.setDateFormatString("yyyy-MM-dd");

        jLabel7.setText("đến");

        ThoiGianDen.setDateFormatString("yyyy-MM-dd");

        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)
                        .addComponent(MaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(MaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(MaKhachHang)
                            .addComponent(ThoiGianTu, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(btnLamMoi)))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(ThoiGianDen, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnLamMoi, btnTimKiem});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(MaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(MaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ThoiGianDen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(MaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addComponent(ThoiGianTu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTimKiem)
                    .addComponent(btnLamMoi))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnLamMoi, btnTimKiem});

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 96, -1, -1));

        HoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hoá đơn", "Mã khách hàng", "Mã nhân viên", "Mã giảm giá", "Ngày tạo", "Tổng tiền", "Giảm giá", "Thành tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(HoaDon);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 770, 206));

        ChiTietHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Số lượng", "Đơn giá", "Thành tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(ChiTietHoaDon);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 481, 846, 200));
    }// </editor-fold>//GEN-END:initComponents

    private void XuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XuatActionPerformed
        int option = JOptionPane.showConfirmDialog(
                this,
                "Bạn có muốn in hóa đơn không?",
                "Xác nhận in hóa đơn",
                JOptionPane.YES_NO_OPTION
        );

        if (option == JOptionPane.YES_OPTION) {
            Document document = new Document();
            try {
                String userHome = System.getProperty("user.home");
                String downloadsPath = userHome + "/Downloads/HoaDon.pdf";

                PdfWriter.getInstance(document, new FileOutputStream(downloadsPath));
                document.open();

                Font font = FontFactory.getFont(FontFactory.HELVETICA, 12);

                document.add(new Paragraph("HOA DON BAN HANG", font));
                document.add(new Paragraph("Ngay: " + new java.util.Date(), font));
                document.add(new Paragraph(" "));

                PdfPTable table = new PdfPTable(8);
                table.setWidthPercentage(100);

                table.addCell(new Paragraph("Ma hoa don", font));
                table.addCell(new Paragraph("Ma khach hang", font));
                table.addCell(new Paragraph("Ma nhan vien", font));
                table.addCell(new Paragraph("Ma giam gia", font));
                table.addCell(new Paragraph("Ngay tao", font));
                table.addCell(new Paragraph("Tong tien", font));
                table.addCell(new Paragraph("Giam gia", font));
                table.addCell(new Paragraph("Thanh tien", font));

                DefaultTableModel model = (DefaultTableModel) HoaDon.getModel();
                int rowCount = model.getRowCount();

                for (int i = 0; i < rowCount; i++) {
                    String maHoaDon = model.getValueAt(i, 0) != null ? model.getValueAt(i, 0).toString() : "";
                    String maKhachHang = model.getValueAt(i, 1) != null ? model.getValueAt(i, 1).toString() : "";
                    String maNhanVien = model.getValueAt(i, 2) != null ? model.getValueAt(i, 2).toString() : "";
                    String maGiamGia = model.getValueAt(i, 3) != null ? model.getValueAt(i, 3).toString() : "";
                    String ngayTao = model.getValueAt(i, 4) != null ? model.getValueAt(i, 4).toString() : "";
                    String tongTien = model.getValueAt(i, 5) != null ? model.getValueAt(i, 5).toString() : "";
                    String giamGia = model.getValueAt(i, 6) != null ? model.getValueAt(i, 6).toString() : "";
                    String thanhTien = model.getValueAt(i, 7) != null ? model.getValueAt(i, 7).toString() : "";

                    table.addCell(new Paragraph(maHoaDon, font));
                    table.addCell(new Paragraph(maKhachHang, font));
                    table.addCell(new Paragraph(maNhanVien, font));
                    table.addCell(new Paragraph(maGiamGia, font));
                    table.addCell(new Paragraph(ngayTao, font));
                    table.addCell(new Paragraph(tongTien, font));
                    table.addCell(new Paragraph(giamGia, font));
                    table.addCell(new Paragraph(thanhTien, font));
                }

                document.add(table);
                document.close();

                JOptionPane.showMessageDialog(this, "Xuất hóa đơn thành công: " + downloadsPath);
            } catch (DocumentException | IOException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Lỗi khi xuất hóa đơn: " + e.getMessage());
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Lỗi không xác định: " + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Bạn đã hủy in hóa đơn.");
        }
    }//GEN-LAST:event_XuatActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
// Lấy dữ liệu từ các trường nhập liệu
        String maHoaDon = MaHoaDon.getText().trim();
        String maNhanVien = MaNhanVien.getText().trim();
        String maKhachHang = MaKhachHang.getText().trim();

// Lấy ngày từ JDateChooser và chuyển đổi sang LocalDate
        Date tuNgayUtil = ThoiGianTu.getDate();
        Date denNgayUtil = ThoiGianDen.getDate();

        LocalDate tuNgay = null;
        LocalDate denNgay = null;

// Xử lý trường hợp người dùng không chọn ngày
        if (tuNgayUtil != null) {
            tuNgay = tuNgayUtil.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        }

        if (denNgayUtil != null) {
            denNgay = denNgayUtil.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        }

// Lấy model của bảng và xóa dữ liệu cũ
        DefaultTableModel model = (DefaultTableModel) HoaDon.getModel();
        model.setRowCount(0);

// Lấy danh sách hóa đơn từ repository
        ArrayList<HoaDon> hoaDons = hoaDonRepo.getAllHoaDon();

// Duyệt qua danh sách hóa đơn
        for (HoaDon hoaDon : hoaDons) {
            boolean matches = true;

            // Kiểm tra mã hóa đơn
            if (!maHoaDon.isEmpty() && !hoaDon.getMaHoaDon().contains(maHoaDon)) {
                matches = false;
            }

            // Kiểm tra mã nhân viên
            if (!maNhanVien.isEmpty() && !hoaDon.getMaNhanVien().contains(maNhanVien)) {
                matches = false;
            }

            // Kiểm tra mã khách hàng
            if (!maKhachHang.isEmpty() && !hoaDon.getMaKhachHang().contains(maKhachHang)) {
                matches = false;
            }

            // Kiểm tra thời gian từ và đến
            if (tuNgay != null && denNgay != null) {
                LocalDate ngayTaoHoaDon = hoaDon.getNgayTao();

                // Kiểm tra xem ngày tạo hóa đơn có nằm trong khoảng thời gian cho phép
                if (ngayTaoHoaDon != null
                        && (ngayTaoHoaDon.isBefore(tuNgay) || ngayTaoHoaDon.isAfter(denNgay))) {
                    matches = false;
                }
            }

            // Nếu tất cả các điều kiện đều đúng, thêm hóa đơn vào bảng
            if (matches) {
                model.addRow(new Object[]{
                    hoaDon.getMaHoaDon(),
                    hoaDon.getMaKhachHang(),
                    hoaDon.getMaNhanVien(),
                    hoaDon.getMaPhieuGiamGia(),
                    hoaDon.getNgayTao(),
                    hoaDon.getTongTien(),
                    hoaDon.getSoTienGiam(),
                    hoaDon.getThanhTien()
                });
            }

    }//GEN-LAST:event_btnTimKiemActionPerformed
    }
    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        lamMoiForm();
    }//GEN-LAST:event_btnLamMoiActionPerformed
    private void lamMoiForm() {
        MaHoaDon.setText("");
        MaKhachHang.setText("");
        MaNhanVien.setText("");
        ThoiGianTu.setDate(null);
        ThoiGianDen.setDate(null);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ChiTietHoaDon;
    private javax.swing.JTable HoaDon;
    private javax.swing.JTextField MaHoaDon;
    private javax.swing.JTextField MaKhachHang;
    private javax.swing.JTextField MaNhanVien;
    private com.toedter.calendar.JDateChooser ThoiGianDen;
    private com.toedter.calendar.JDateChooser ThoiGianTu;
    private javax.swing.JButton Xuat;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
